spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/newdb
    username: root
    password: Neutrone123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop

      spring:
        profiles: test
        datasource:
          driverClassName: org.h2.Driver
          url: jdbc:h2:mem:newbd
          username: root
          password: Neutrone123
        jpa:
          hibernate.ddl-auto: create-drop
